---
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: "Checkout Github Action"
        uses: actions/checkout@master
      -
        name: "Set up Java version"
        uses: actions/setup-java@v1
        with:
          java-version: "8"
      -
        inputs:
          gradleOptions: "-Xmx3072m"
          gradleWrapperFile: gradlew
          javaHomeOption: JDKVersion
          jdkArchitectureOption: x64
          jdkVersionOption: "1.8"
          publishJUnitResults: false
          tasks: build
          testResultsFiles: "**/TEST-*.xml"
          workingDirectory: ""
        task: Gradle@2
      -
        name: "Run Azure webapp deploy action using publish profile credentials"
        uses: azure/webapps-deploy@v2
        with:
          app-name: sport-platform-apm
          package: "${{ github.workspace }}/target/*.jar"
          publish-profile: "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9730D81A480C4C8FAE01EAED22F1CD5C }}"
          slot-name: Production
name: "Azure App Service - sport-platform-apm(Production), Build and deploy Spring app"
true:
  push:
    branches:
      - main
